### ISSUE TITLE
meta type is missing, After upgrade from 0.0.1 to 0.3.3

### ISSUE THREAD

**Issue by jzsplk** [MichaelDuo/saga-resource#7]
After upgrade from 0.0.1 to 0.3.3, 
The resource's `meta` type is missing.

![image](https://user-images.githubusercontent.com/19876781/59200256-696e4600-8bca-11e9-95c7-8ba280d30b71.png)

**Comment by MichaelDuo** [comment]
fixed in v0.3.3
